apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels: 
        tier: frontend
    spec:
      containers:
      - name: app1
        image: kiran2361993/loadbalancerimage:v1
        ports:
        - containerPort: 80
