apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels belong to deployment
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels: # these labels should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  label: nginx-service
spec:
  selector:
    matchLabels:
      app: nginx
      project: roboshop
      component: frontend
    ports:
    - name: name-of-service
      port: 80
      targetPort: 80
      protocol: TCP
