apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deplyoment
  labels:
    env: production
spec: 
  replicas: 5
  selector:
    matchLabels:
      env: production
      app: frontend
  template:
    metadata:
      labels:
        env: production
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    env: production
    app: frontend
  ports:
  - name: name-of-the-service
    port: 8082
    targetPort: 80
    protocol: TCP