apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replica
  labels:  # Move labels under metadata
    env: prod 
    app: frontend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: prod
  template: 
    metadata: 
      labels:
        app: frontend
        env: prod  # Correct the typo here from 'end' to 'env'
    spec:
      containers:
      - name: nginx
        image: nginx
