apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replica
  labels: 
    app: frontend
    env: production
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: frontend
      env: production
  template: 
    metadata:
      labels: 
        app: frontend
        env: production
    spec:
      containers:
      - name: nginx 
        image: nginx