apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ReplicaSet
  labels: 
    env: prod 
    app: frontend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: prod
  template: 
    metadata: 
      labels:
        app: frontend
        env: prod 
    spec:
      containers:
      - name: nginx
        image: nginx